base_url: "https://zyl.gay"
title: zyl's website
description: "zyl's website."
sass_styles: [index.scss]
images_per_page: 10
blog_posts_per_page: 20
cdn_url: "https://i.zyl.gay"
s3_prefix: # no longer prefixed
