base_url: "https://zyl.gay"
title: zyl is gay
description: "zyl's website."
theme_color: "#ffc4fc"
sass_styles: [index.scss, pet.scss, click.scss]
cdn_url: "https://i.zyl.gay"
code_theme: base16-ocean.dark

resources:
  blog:
    source_path: blog
    output_path_resources: blog
    output_path_lists: blog
    resource_template: blog/resource.tera
    resource_list_template: blog/list.tera
    tag_list_template: basic-link-list.tera
    rss_template: blog/rss.tera
    rss_title: zyl's blog
    rss_description: feed of recent blog posts on zyl's website.
    list_title: blog
    tag_list_title: blog tags
    resource_name_plural: blog posts
    resources_per_page: 20
  images:
    source_path: images
    output_path_resources: i
    output_path_lists: images
    resource_template: image/resource.tera
    resource_list_template: image/list.tera
    tag_list_template: basic-link-list.tera
    rss_template: image/rss.tera
    rss_title: zyl's images
    rss_description: feed of newly uploaded images from zyl's website.
    list_title: images
    tag_list_title: image tags
    resource_name_plural: images
    resources_per_page: 10
